language: node_js

os: linux
dist: jammy

node_js:
    - lts/*

notifications:
    email:
        on_success: never

script:
  - npm install codecov -g
  - npm i
  - npm test

after_success:
  - codecov
